### ISSUE TITLE
Employee postData front End BackEnd Connectivity

### ISSUE THREAD

**Issue by Aarti1505** [narkhedepratik/ApnaFainanceUI_Repo#2]
employee class is already created. cross check the fields.
call function onRegistration() in AddEmployeeComponent.ts 
Create one Service for Employee(employee.service)
create post data method for Employee class in service(cross check all the endpoints from backEnd)

**Comment by NileshAkhadkar** [comment]
#2 Employee postData front End BackEnd Connectivity completed.
